server:
  port: 9000
spring:
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.103.26.35:3306/kong?characterEncoding=utf-8
    username: kong
    password: kong
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true


