server:
  port: 9000
spring:
  servlet:
    multipart:
      max-file-size: 5MB # 限制文件上传的大小
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/haozhi?useUnicode=true&&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: db136s1ehvo1yn73
    password: cxz307311SJK
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      connection-init-sqls: SET NAMES utf8mb4
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: true


